import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"

import "./globals.css"

import Footer from "@/components/footer"
import Navbar from "@/components/navbar"

const open_sans = Open_Sans({
    subsets: ["latin"],
    variable: "--font-open-sans",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={open_sans.className}>
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    )
}
